---
output:
  html_document:
    df_print: paged
---

```{r setup, echo = FALSE}
library(knitr)
```

:::: {style="display: grid; grid-template-columns: 2fr 5fr 1fr; grid-column-gap: 20px"}

::: {}
---

## John P. Ryan

---

[Home](john-p-ryan.github.io)

[Research](https://john-p-ryan.github.io/research/)

[CV](https://john-p-ryan.github.io/Ryan_CV_jul23.pdf)

---

[Email](mailto:john.p.ryan@wisc.edu)

[GitHub](https://github.com/john-p-ryan)

---

:::

::: {}

---

### I passed my prelims!   
*by John Ryan*   
22 June 2023

---

> "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way" - 
> Charles Dickens, A Tale of Two Cities

This quote encapsulates my experience during my first year in the econ PhD at UW-Madison. 
It was a tough journey, but it has all paid off. 
That is because I passed my preliminary exams! 
There has been a lot of anxiety leading up to this moment, but I have learned so much in the past year.

Since I passed, I have about 2 months of time to rest, and work on a few projects, one of which has been building this website. 
I plan on learning Julia, getting better at Git / Github, sketching out a research idea or two, polish my senior thesis, and maybe contribute to some other projects. 

[back to home](https://john-p-ryan.github.io/)

:::

::::