---
title: ""
listing:
  id: landing-posts
  contents: posts
  sort: "date desc"
  type: table # Options: default, grid, table
  categories: false # Set to true if you want to show tags
  sort-ui: false
  filter-ui: false
  fields: [date, title]
  date-format: "MM-DD-YYYY"
---
```{=html}
<style>
  /* Force the date column to not wrap text */
  .listing-date {
    white-space: nowrap !important;
    min-width: 100px; /* Optional: ensures a minimum width */
  }
</style>

::: {.grid}

::: {.g-col-12 .g-col-sm-4}
{{< include _profile.qmd >}}
:::

::: {.g-col-12 .g-col-sm-7 .g-start-sm-6}


### Welcome!

My name is John Ryan and I am a fourth year PhD student in economics at the University of Wisconsin - Madison, originally from Charleston, SC. 

My interests lie in public finance, computational methods, and macroeconomics. My current work is related to flood insurance and immigration policy. My previous work includes open source modeling for [Inverse-Optimal Tax methods](https://github.com/PSLmodels/InverseOptimalTax/tree/main), and [reducing bias for machine learning estimators](https://www.banglajol.info/index.php/JStR/article/view/67466/45250). 

Before starting my PhD, I completed my BS in Economics, Mathematics and Statistics at the University of South Carolina (the real USC). Go Gamecocks!

Feel free to contact me by email at [john.p.ryan@wisc.edu](mailto:john.p.ryan@wisc.edu) if you have any questions.

---

### Posts


::: {#landing-posts}
:::

:::

:::